version: "3.9"
networks:
  default:
    external:
      name: megaphone-network
services:
  ############################
  # Resources + Dapr sidecar
  ############################
  resources:
    container_name: resources
    restart: always
    image: ds1520plusregistry.azurecr.io/resources:latest
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
      - DOTNET_VERSION=5.0.3
      - ASPNET_VERSION=5.0.3
      - DAPR_HTTP_PORT=3500
      - DAPR_GRPC_PORT=50001
      - INSTRUMENTATION_KEY=9a7662a3-3a20-498b-b88e-324697bd783d
      - USE-VOLUME-STORAGE=true
    volumes: 
        - "/volume2/docker/data/megaphone/resources:/data"
    ports:
     - "10000:80" # app-port
     - "10001:50001" # dapr-grpc-port
     - "10002:3500" # dapr-http-port 
     - "10003:9090" # metrics-port
     - "10004:7777" # profile-port
  dapr_resources:
    container_name: dapr_resources
    restart: always
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "resources",
     "-app-port", "80",
     "-dapr-grpc-port", "50001",
     "-dapr-http-port", "3500",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components",
     "-config", "/configurations/opentelemetry-collector-configuration.yml"]
    volumes:
        - "./configurations/opentelemetry-collector-configuration.yml:/configurations/opentelemetry-collector-configuration.yml"
        - "./components/:/components"
    depends_on:
      - resources
    network_mode: "service:resources" 
  ############################
  # Crawler + Dapr sidecar
  ############################
  crawler:
    container_name: crawler
    restart: always
    image: ds1520plusregistry.azurecr.io/crawler:latest
    depends_on:
      - resources
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
      - DOTNET_VERSION=5.0.3
      - ASPNET_VERSION=5.0.3
      - DAPR_HTTP_PORT=3500
      - DAPR_GRPC_PORT=50001
      - INSTRUMENTATION_KEY=9a7662a3-3a20-498b-b88e-324697bd783d
    ports:
      - "20000:80" # app-port
      - "20001:50001" # dapr-grpc-port
      - "20002:3500" # dapr-http-port 
      - "20003:9090" # metrics-port
      - "20004:7777" # profile-port
  dapr_crawler:
    container_name: dapr_crawler
    restart: always
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "crawler",
     "-app-port", "80",
     "-app-max-concurrency","20",
     "-dapr-grpc-port", "50001",
     "-dapr-http-port", "3500",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components",
     "-config", "/configurations/opentelemetry-collector-configuration.yml"]
    volumes:
        - "./configurations/opentelemetry-collector-configuration.yml:/configurations/opentelemetry-collector-configuration.yml"
        - "./components/:/components"
    depends_on:
      - crawler
    network_mode: "service:crawler"
  ############################
  # Feeds + Dapr sidecar
  ############################
  feeds:
    container_name: feeds
    restart: always
    image: ds1520plusregistry.azurecr.io/feeds:latest
    depends_on:
      - api
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
      - DOTNET_VERSION=5.0.3
      - ASPNET_VERSION=5.0.3
      - DAPR_HTTP_PORT=3500
      - DAPR_GRPC_PORT=50001
      - INSTRUMENTATION_KEY=9a7662a3-3a20-498b-b88e-324697bd783d
      - USE-VOLUME-STORAGE=true
      - SCHEDULE-CRAWL-INTERVAL=20
    volumes: 
        - "/volume2/docker/data/megaphone/feeds:/data"
    ports:
      - "30000:80" # app-port
      - "30001:50001" # dapr-grpc-port
      - "30002:3500" # dapr-http-port 
      - "30003:9090" # metrics-port
      - "30004:7777" # profile-port
  dapr_feeds:
    container_name: dapr_feeds
    restart: always
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "feeds",
     "-app-port", "80",
     "-dapr-grpc-port", "50001",
     "-dapr-http-port", "3500",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components",
     "-config", "/configurations/opentelemetry-collector-configuration.yml"]
    volumes:
        - "./configurations/opentelemetry-collector-configuration.yml:/configurations/opentelemetry-collector-configuration.yml"
        - "./components/:/components"
    depends_on:
      - feeds
    network_mode: "service:feeds"
  ############################
  # API + Dapr sidecar
  ############################
  api:
    container_name: api
    restart: always
    image: ds1520plusregistry.azurecr.io/api:latest
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
      - DOTNET_VERSION=5.0.3
      - ASPNET_VERSION=5.0.3
      - DAPR_HTTP_PORT=3500
      - DAPR_GRPC_PORT=50001
      - INSTRUMENTATION_KEY=9a7662a3-3a20-498b-b88e-324697bd783d
      - USE-VOLUME-STORAGE=true
    volumes: 
        - "/volume2/docker/data/megaphone/api:/data"
    ports:
      - "40000:80" # app-port
      - "40001:50001" # dapr-grpc-port
      - "40002:3500" # dapr-http-port 
      - "40003:9090" # metrics-port
      - "40004:7777" # profile-port
  dapr_api:
    container_name: dapr_api
    restart: always
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "api",
     "-app-port", "80",
     "-dapr-grpc-port", "50001",
     "-dapr-http-port", "3500",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components",
     "-config", "/configurations/opentelemetry-collector-configuration.yml"]
    volumes:
        - "./configurations/opentelemetry-collector-configuration.yml:/configurations/opentelemetry-collector-configuration.yml"
        - "./components/:/components"
    depends_on:
      - api
    network_mode: "service:api"
  ############################
  # App + Dapr sidecar
  ############################
  app:
    container_name: app
    restart: always
    image: ds1520plusregistry.azurecr.io/app:latest
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
      - DOTNET_VERSION=5.0.3
      - ASPNET_VERSION=5.0.3
      - DAPR_HTTP_PORT=3500
      - DAPR_GRPC_PORT=50001
      - INSTRUMENTATION_KEY=9a7662a3-3a20-498b-b88e-324697bd783d
    ports:
      - "50000:80" # app-port
      - "50001:50001" # dapr-grpc-port
      - "50002:3500" # dapr-http-port 
      - "50003:9090" # metrics-port
      - "50004:7777" # profile-port
  dapr_app:
    container_name: dapr_app
    restart: always
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "app",
     "-app-port", "80",
     "-dapr-grpc-port", "50001",
     "-dapr-http-port", "3500",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components",
     "-config", "/configurations/opentelemetry-collector-configuration.yml"]
    volumes:
        - "./configurations/opentelemetry-collector-configuration.yml:/configurations/opentelemetry-collector-configuration.yml"
        - "./components/:/components"
    depends_on:
      - app
    network_mode: "service:app"